---

# Gerenciamento de pacotes

- name: Instalacao dos repositorios PHP 7.2
  yum: 
    name: ['https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm', 'https://mirror.webtatic.com/yum/el7/webtatic-release.rpm']
    state: latest
  when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS'

#- name: Atualizacao do Sistema Operacional
#  yum: name=* state=latest update_cache=yes
#  when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS'

- name: Instalacao dos pacotes PHP 7.2
  yum: 
    name: "{{ packages }}"
    state: latest
  when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS'

# Configuracoes

- name: Criando copia de seguranca do /etc/php.ini
  command: cp /etc/php.ini /etc/php.ini_original
  args:
    warn: false
  when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS'

- name: Criando copia de seguranca do /etc/php-fpm.d/www.conf
  command: mv /etc/php-fpm.d/www.conf /etc/php-fpm.d/www.conf_original
  args:
    warn: false
  when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS'

- name: Configurando Timezone do php.ini
  lineinfile:
    dest=/etc/php.ini
    state=present
    regexp=';date.timezone ='
    line='date.timezone = America/Sao_Paulo'
  when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS'

- name: Copiando o arquivo www.conf para o servidor
  copy: src=www.conf dest=/etc/php-fpm.d/www.conf owner=root group=root
  when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS'

- name: Criacao de diretorios utilizados pelo PHP-FPM
  file: path={{item}} state=directory mode=755 owner=nginx group=nginx
  with_items:
    - /var/lib/php/session
    - /var/lib/php/wsdlcache
  notify: Restart php-fpm
  when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS'

...
